### ISSUE TITLE
Allow domain to return zero resources without failing

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns-labs/lula1#589]
### Describe what should be investigated or refactored

In thinking about general workflows for best-practices and STIG's, Lula may want to support the ability to return zero resources from a domain data collection activity. 

Currently the inability to find > 0 resources will fail a Validation as `not evaluated` as there were no items found. 

I thinking about something such as a best practice or STIG - there are at least two primary scenarios:
1. If a resource exists -> perform policy evaluation to determine adherence
2. If a resource does not exist -> there is no applicable evaluation to be done (IE success)

both of these should be drive from the provider policy instead of the domain. This allows the validation author to write a policy that either passes or fails when zero resources are retrieved.

**Comment by meganwolf0** [comment]
I like this issue and agree that auto-failing with no resources isn't great. However, I will say that this will probably need to be coupled with updated validations/tests, as I'm not sure that they all pass with zero input conditions. Since that wasn't a possible outcome I didn't always include that in the testing options. Depending on how the input is structured (e.g., {some-resource: {}} or just {}) will probably impact those policies.

**Comment by brandtkeller** [comment]
use case for this:

https://github.com/defenseunicorns/uds-common/blob/main/tasks/badge.yaml#L215
